version: 2.0

jobs:
  build:
    working_directory: ~/pandemic-tracker-api
    docker:
      - image: cimg/ruby:2.5-node # primary container - where job steps are run
        environment:
          PGHOST: localhost
          PGUSER: development
          RAILS_ENV: test
      - image: cimg/postgres:9.6 # services container
        environment:
          POSTGRES_USER: development
          POSTGRES_DB: pandemic_test
          POSTGRES_PASSWORD: development
    steps:
      - checkout

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: pandemic-tracker-api-{{ checksum "Gemfile.lock" }}

      # install bundler 1.17.3
      - run:
          name: install dependencies
          command: |
            gem install bundler -v 1.17.3

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: pandemic-tracker-api-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      # Database setup
      - run: bundle exec rake db:migrate

      - run:
          name: Run tests
          command: |
            bundle exec rspec
  deploy:
    machine:
      enabled: true

    working_directory: ~/pandemic-tracker-api

    steps:
      - add_ssh_keys:
          fingerprints:
            - "c1:d1:19:bb:4c:d0:7b:b3:01:6f:4f:b3:2b:b4:45:55"
      - checkout
      - run:
          name: Push Master to Production
          command: |
            git push https://github.com/xihai01/pandemic-tracker-api.git main:production

workflows:
  version: 2
  build-and-test-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: production
      - deploy:
          filters:
            branches:
              ignore: production
          requires:
            - build
